// Barrel re-exports for clean imports
export * from './dashboard.service';
export * from './customers.service';
export * from './leads.service';
export * from './products.service';
export * from './orders.service';
export * from './invoices.service';
export * from './finance.service';
export * from './inventory.service';
export * from './projects.service';
export * from './hr.service';
export * from './logistics.service';
export * from './tasks.service';
export * from './team.service';
export * from './marketing.service';
export * from './admin.service';
export * from './search.service';
export * from './notifications.service';
export * from './erp.service';
